// Capability-free starter-plugin scaffold generated by
// `scripts/scaffold-tassadar-capability-free-starter-plugin.py`.
// TODO: copy the relevant pieces into
// `crates/psionic-runtime/src/tassadar_post_article_starter_plugin_runtime.rs`
// and replace every TODO with plugin-specific logic.

pub const STARTER_PLUGIN_EXAMPLE_WORDS_ID: &str = "plugin.example.words";
pub const STARTER_PLUGIN_EXAMPLE_WORDS_TOOL_NAME: &str = "plugin_example_words";
pub const STARTER_PLUGIN_EXAMPLE_WORDS_INPUT_SCHEMA_ID: &str = "plugin.example.words.input.v1";
pub const STARTER_PLUGIN_EXAMPLE_WORDS_OUTPUT_SCHEMA_ID: &str = "plugin.example.words.output.v1";

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExampleWordsRequest {
    // TODO: replace the sample field set with plugin-specific request fields.
    pub text: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExampleWordsResponse {
    // TODO: replace the sample field set with plugin-specific response fields.
    pub value: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExampleWordsConfig {
    pub packet_size_limit_bytes: usize,
}

impl Default for ExampleWordsConfig {
    fn default() -> Self {
        Self {
            packet_size_limit_bytes: 16 * 1024,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExampleWordsInvocationOutcome {
    pub receipt: StarterPluginInvocationReceipt,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<ExampleWordsResponse>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refusal: Option<StarterPluginRefusal>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExampleWordsRuntimeCaseStatus {
    ExactSuccess,
    TypedMalformedPacket,
    TypedRefusal,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExampleWordsRuntimeCase {
    pub case_id: String,
    pub status: ExampleWordsRuntimeCaseStatus,
    pub codec_id: String,
    pub request_packet_digest: String,
    pub response_or_refusal_schema_id: String,
    pub response_or_refusal_digest: String,
    pub receipt: StarterPluginInvocationReceipt,
    pub detail: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExampleWordsRuntimeBundle {
    pub schema_version: u16,
    pub bundle_id: String,
    pub plugin_id: String,
    pub plugin_version: String,
    pub manifest_id: String,
    pub artifact_id: String,
    pub packet_abi_version: String,
    pub mount_envelope_id: String,
    pub tool_projection: StarterPluginToolProjection,
    pub negative_claim_ids: Vec<String>,
    pub case_rows: Vec<ExampleWordsRuntimeCase>,
    pub claim_boundary: String,
    pub summary: String,
    pub bundle_digest: String,
}

const EXAMPLE_WORDS_REFUSAL_SCHEMA_IDS: &[&str] = &[
    STARTER_PLUGIN_REFUSAL_SCHEMA_INVALID_ID,
    STARTER_PLUGIN_REFUSAL_PACKET_TOO_LARGE_ID,
    STARTER_PLUGIN_REFUSAL_UNSUPPORTED_CODEC_ID,
];

const EXAMPLE_WORDS_NEGATIVE_CLAIM_IDS: &[&str] = &[
    "todo_replace_with_plugin_specific_negative_claim_1",
    "todo_replace_with_plugin_specific_negative_claim_2",
];

pub const TASSADAR_POST_ARTICLE_PLUGIN_EXAMPLE_WORDS_RUNTIME_BUNDLE_REF: &str =
    "fixtures/tassadar/runs/tassadar_post_article_example_words_v1/tassadar_post_article_example_words_bundle.json";
pub const TASSADAR_POST_ARTICLE_PLUGIN_EXAMPLE_WORDS_RUN_ROOT_REF: &str =
    "fixtures/tassadar/runs/tassadar_post_article_example_words_v1";

// TODO: add this row inside STARTER_PLUGIN_REGISTRATIONS.
const EXAMPLE_WORDS_REGISTRATION_TEMPLATE: StarterPluginRegistration = StarterPluginRegistration {
    plugin_id: STARTER_PLUGIN_EXAMPLE_WORDS_ID,
    plugin_version: STARTER_PLUGIN_VERSION,
    tool_name: STARTER_PLUGIN_EXAMPLE_WORDS_TOOL_NAME,
    input_schema_id: STARTER_PLUGIN_EXAMPLE_WORDS_INPUT_SCHEMA_ID,
    success_output_schema_id: STARTER_PLUGIN_EXAMPLE_WORDS_OUTPUT_SCHEMA_ID,
    refusal_schema_ids: EXAMPLE_WORDS_REFUSAL_SCHEMA_IDS,
    replay_class_id: "deterministic_replayable",
    capability_class: StarterPluginCapabilityClass::LocalDeterministic,
    capability_namespace_ids: NO_CAPABILITY_NAMESPACE_IDS,
    negative_claim_ids: EXAMPLE_WORDS_NEGATIVE_CLAIM_IDS,
    mount_envelope_id: "mount.plugin.example.words.no_capabilities.v1",
    manifest_id: "manifest.plugin.example.words.v1",
    artifact_id: "artifact.plugin.example.words.v1",
    runtime_bundle_id: "tassadar.post_article.plugin_example_words.runtime_bundle.v1",
    runtime_bundle_ref: TASSADAR_POST_ARTICLE_PLUGIN_EXAMPLE_WORDS_RUNTIME_BUNDLE_REF,
    runtime_run_root_ref: TASSADAR_POST_ARTICLE_PLUGIN_EXAMPLE_WORDS_RUN_ROOT_REF,
    tool_description: "TODO: replace with one bounded capability-free tool description.",
    bridge_exposed: false,
    catalog_exposed: false,
    catalog: None,
};

pub fn example_words_tool_projection() -> StarterPluginToolProjection {
    let registration = starter_plugin_registration(STARTER_PLUGIN_EXAMPLE_WORDS_ID);
    starter_plugin_tool_projection_from_registration(
        registration,
        serde_json::json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "text": {"type": "string"}
            },
            "required": ["text"]
        }),
    )
}

pub fn invoke_example_words_json_packet(
    codec_id: &str,
    packet: &[u8],
    config: &ExampleWordsConfig,
) -> ExampleWordsInvocationOutcome {
    let _ = (codec_id, packet, config);
    // TODO: implement decode, typed refusal, success response, and receipt creation.
    todo!("implement invoke_example_words_json_packet")
}

pub fn build_example_words_runtime_bundle() -> ExampleWordsRuntimeBundle {
    // TODO: add success and refusal fixtures, then compute the stable digest.
    todo!("implement build_example_words_runtime_bundle")
}
